import { Palette } from "std-widgets.slint";
import { MagicText } from "@vivi/magic.slint";
import { Catppuccin, CatppuccinPalette } from "../styling.slint";

export enum MessageType {
    Error,
    Info
}

export component MessageText inherits MagicText {
    in property <MessageType> message_type;

    color: get_color();

    function get_color() -> color {
        let catppuccin_palette = Palette.color_scheme == ColorScheme.light
            ? Catppuccin.latte
            : Catppuccin.macchiato;
        return root.message_type == MessageType.Error
            ? catppuccin_palette.red
            : catppuccin_palette.blue;
    }
}
