import {
    ButtonAction,
    ComboBox,
    FilledButton,
    GroupBox,
    MagicText,
    OutlineButton,
} from "@vivi/magic.slint";
import { MessageText, SlintMessageType } from "text.slint";
import { VerticalBox, } from "std-widgets.slint";
import { Globals, } from "../globals.slint";

export component MidiIo inherits GroupBox {
    title: group_title;
    width: 680px;
    forward-focus: input_devices_combo;

    in property <string> group_title;

    in property input_devices_model <=> input_devices_combo.model;
    in-out property <int> input_selected_port_index;
    callback input_connect_port();
    callback input_refresh_devices();
    public function input_focus() {
        input_devices_combo.focus();
    }
    public function input_show_connected_device_name(name: string, message_type: SlintMessageType) {
        input_connected_device_name_text.text = name;
        input_connected_device_name_text.message_type = message_type;
    }

    in property output_devices_model <=> output_devices_combo.model;
    in-out property <int> output_selected_port_index;
    callback output_connect_port();
    callback output_refresh_devices();
    public function output_focus() {
        output_devices_combo.focus();
    }
    public function output_show_connected_device_name(name: string, message_type: SlintMessageType) {
        output_connected_device_name_text.text = name;
        output_connected_device_name_text.message_type = message_type;
    }

    VerticalBox {
        padding: 0px;
        HorizontalLayout {
            MagicText {
                text: "MIDI Input";
                vertical_alignment: center;
            }
            VerticalLayout {
                padding_left: Globals.horizontal_padding;
                padding_right: Globals.horizontal_padding * 2;
                input_devices_combo := ComboBox {
                    current_index: root.input_selected_port_index;
                    changed current_index => {
                        root.input_selected_port_index = self.current_index;
                    }
                    height: Globals.control_height;
                    width: 395px;
                }
            }
            VerticalLayout {
                FilledButton {
                    text: "Connect";
                    action: ButtonAction.primary;
                    clicked => {
                        root.input_connect_port()
                    }
                    height: Globals.control_height;
                    width: Globals.button_width;
                }
            }
        }
        GridLayout {
            VerticalLayout {
                col: 0;
                MagicText {
                    text: "Connected: ";
                    horizontal_alignment: left;
                    vertical_alignment: center;
                }
            }
            VerticalLayout {
                col: 1;
                input_connected_device_name_text := MessageText {
                    horizontal_alignment: left;
                    vertical_alignment: center;
                }
            }
            VerticalLayout {
                col: 2;
                OutlineButton {
                    text: "Refresh Ports";
                    clicked => {
                        root.input_refresh_devices()
                    }
                    height: Globals.control_height;
                    width: Globals.button_width;
                }
            }
        }
        HorizontalLayout {
            MagicText {
                text: "MIDI Output";
                vertical_alignment: center;
            }
            VerticalLayout {
                padding_left: Globals.horizontal_padding;
                padding_right: Globals.horizontal_padding * 2;
                output_devices_combo := ComboBox {
                    current_index: root.output_selected_port_index;
                    changed current_index => {
                        root.output_selected_port_index = self.current_index;
                    }
                    height: Globals.control_height;
                    width: 395px;
                }
            }
            VerticalLayout {
                FilledButton {
                    text: "Connect";
                    action: ButtonAction.primary;
                    clicked => {
                        root.output_connect_port()
                    }
                    height: Globals.control_height;
                    width: Globals.button_width;
                }
            }
        }
        GridLayout {
            VerticalLayout {
                col: 0;
                MagicText {
                    text: "Connected: ";
                    horizontal_alignment: left;
                    vertical_alignment: center;
                }
            }
            VerticalLayout {
                col: 1;
                output_connected_device_name_text := MessageText {
                    horizontal_alignment: left;
                    vertical_alignment: center;
                }
            }
            VerticalLayout {
                col: 2;
                OutlineButton {
                    text: "Refresh Ports";
                    clicked => {
                        root.output_refresh_devices()
                    }
                    height: Globals.control_height;
                    width: Globals.button_width;
                }
            }
        }
    }
}