import { ButtonAction, FilledButton, MagicText, MagicWindow } from "@vivi/magic.slint";
import { Palette } from "std-widgets.slint";
import { Globals } from "globals.slint";
import { Catppuccin, } from "styling.slint";

export component AboutWindow inherits MagicWindow {
    init => {
        Palette.color-scheme = ColorScheme.dark;
        close_scope.focus();
    }
    background: Globals.window_background;
    title: window_title;
    preferred-width: 800px;
    preferred-height: 320px;
    icon: Globals.icon;

    in property <string> window_title;
    in property <string> app_title;
    in property <string> version;
    in property <string> copyright;
    in property <string> license;
    in property <string> project_link;

    callback open_project_link();
    callback close_window();

    close_scope := FocusScope {
        key-pressed(event) => {
            if (event.text == Key.Escape || event.text == Key.Return) {
                root.close_window();
                return EventResult.accept;
            }
            EventResult.reject
        }

        VerticalLayout {
            padding: 16px;
            spacing: 16px;

            HorizontalLayout {
                spacing: 20px;

                Image {
                    source: Globals.icon;
                    width: 260px;
                    height: 260px;
                    image-fit: contain;
                }

                VerticalLayout {
                    alignment: center;
                    spacing: 8px;

                    MagicText {
                        text: root.app_title;
                        font-size: 32px;
                    }

                    MagicText {
                        text: "Version " + root.version;
                    }

                    MagicText {
                        text: root.copyright;
                    }

                    TouchArea {
                        mouse-cursor: pointer;
                        clicked => { root.open_project_link(); }

                        MagicText {
                            text: root.project_link;
                            color: Catppuccin.macchiato.blue;
                        }
                    }

                    MagicText {
                        text: "Licence: " + root.license;
                    }
                }
            }

            HorizontalLayout {
                alignment: start;

                FilledButton {
                    text: "Close";
                    height: Globals.control_height;
                    width: Globals.button_width;
                    action: ButtonAction.primary;
                    clicked => { root.close_window(); }
                }
            }
        }
    }
}
