import {
    ComboBox,
    FilledButton,
    MagicHorizontalBox,
    MagicVerticalBox,
    MagicText,
    MagicWindow
} from "@vivi/magic.slint";

export component MainWindow inherits MagicWindow {
    width: 400px;
    height: 300px;
    title: window_title;
    icon: Globals.icon;

    in property <string> window_title;

    GridLayout {
        spacing: 5px;
        Image {
            source: Globals.icon;
            width: 50px; height: 50px;
        }
        MagicText {
            text: "Input:";
            vertical-alignment: center;
        }
        VerticalLayout {
            padding-right: 10px;
            padding-top: 10px;
            ComboBox {
                model: [
                    { text: "First" },
                    { text: "Second" },
                    { text: "Third" }
                ];
                current-index: 0;
                height: 30px;
            }
        }
    }
}

global Globals {
    out property<image> icon: @image-url("images/Midi port black on red 512.png");
}
