import {
    ComboBox,
    MagicText,
    MagicWindow
} from "@vivi/magic.slint";

export component MainWindow inherits MagicWindow {
    min-width: 500px; // Min is also initial
    min-height: 200px; // Min is also initial
    max-height: 600px; // Min does not work if max not set.
    title: window_title;
    icon: Globals.icon;

    in property midi_outputs_model <=> midi-outputs-combo.model;
    in property <string> window_title;
    
    callback midi_output_changed(index: int);

    GridLayout {
        spacing: 5px;
        Image {
            source: Globals.icon;
            width: 50px; height: 50px;
        }
        MagicText {
            text: "MIDI Output:";
            vertical-alignment: center;
        }
        VerticalLayout {
            padding-right: 10px;
            padding-top: 10px;
            midi-outputs-combo := ComboBox {
                current-index: 0;
                changed current-index => {
                    root.midi_output_changed(self.current-index)
                }
                height: 30px;
            }
        }
    }
}

global Globals {
    out property<image> icon: @image-url("images/Midi port black on red 512.png");
}
