import {
    ComboBox,
    MagicText,
    MagicWindow,
    OutlineButton,
} from "@vivi/magic.slint";

import { MessageText, MessageType } from "components/message_text.slint";

export component MainWindow inherits MagicWindow {
    width: 600px;
    height: 200px;
    title: window_title;
    icon: Globals.icon;

    in property midi_outputs_model <=> midi-outputs-combo.model;
    in property <string> window_title;
    
    callback midi_output_changed(index: int);
    callback refresh_midi_outputs();

    public function show_message(message: string, message_type: MessageType) {
        message-text.text = message;
        message-text.message-type = message_type;
    }

    GridLayout {
        HorizontalLayout {
            row: 0;
            VerticalLayout {
                padding-right: 5px;
                Image {
                    source: Globals.icon;
                    width: 50px; height: 50px;
                }
            }
            MagicText {
                text: "MIDI Output:";
                vertical-alignment: center;
                width: 100px;
            }
            VerticalLayout {
                padding-left: 5px;
                padding-top: 10px;
                padding-right: 10px;
                midi-outputs-combo := ComboBox {
                    current-index: 0;
                    changed current-index => {
                        root.midi_output_changed(self.current-index)
                    }
                    height: 30px;
                    width: 280px;
                }
            }
            VerticalLayout {
                padding-top: 10px;
                OutlineButton {
                    text: "Refresh Ports";
                    clicked => {
                        root.refresh_midi_outputs()
                    }
                    height: 30px;
                    width: 140px;
                }
            }
        }
        HorizontalLayout {
            row: 1;
            padding-top: 105px;
            Rectangle {
                width: root.width;
                height: 50px;
                message-text := MessageText {
//                    text: "This crate is the main entry point for embedding user interfaces.";
//                    color: blue;
                    vertical-alignment: center;
                }
            }
        }
    }
}

global Globals {
    out property<image> icon: @image-url("images/Midi port black on red 512.png");
}
