import {
    ButtonAction,
    ComboBox,
    FilledButton,
    GroupBox,
    MagicText,
    MagicWindow,
} from "@vivi/magic.slint";
import { MessageText, MessageType, ParamName, ParamValue } from "components/text.slint";
import { MidiIo } from "components/midi_io.slint";
import { Globals } from "globals.slint";
import { Palette, VerticalBox, } from "std-widgets.slint";

export component MainWindow inherits MagicWindow {
    background: get_background_color();
    width: 700px;
    // Needs to be big enough to include everything down to the first status bar line.
    // Expands automatically if the status message does not fit.
    min_height: 505px;
    title: window_title;
    icon: Globals.icon;
    forward-focus: editor;

    in property depth <=> depth_value.text;
    in property root_freq <=> root_freq_value.text;
    in property stretch <=> stretch_value.text;
    in property skew <=> skew_value.text;
    in property mode_offset <=> mode_offset_value.text;
    in property <int> selected_pitch_table_index;
    in property steps <=> steps_value.text;
    in property pitch_tables_model <=> pitch_tables_combo.model;
    in property <string> window_title;

    callback selected_pitch_table_changed(index: int);
//    callback update_tuning();

//    public function focus_update_tuning_button() {
//        update_tuning_button.focus();
//    }

    function get_background_color() -> color {
        return Palette.color_scheme == ColorScheme.light ? #BDDFCC : #123735;
    }

    public function show_message(message: string, message_type: MessageType) {
        message_text.text = message;
        message_text.message_type = message_type;
    }

    public function show_pitchgrid_connection_status(message: string, message_type: MessageType) {
        pitchgrid_connection_status_text.text = message;
        pitchgrid_connection_status_text.message_type = message_type;
    }

    in property editor_input_ports_model <=> editor.input_ports_model;
    in-out property <int> editor_input_selected_port_index <=> editor.input_selected_port_index;
    callback editor_input_connect_port <=> editor.input_connect_port;
    callback editor_input_refresh_ports <=> editor.input_refresh_ports;
    public function editor_input_focus() {
        editor.input_focus();
    }
    public function editor_input_show_connected_port_name(name: string, message_type: MessageType) {
        editor.input_show_connected_port_name(name, message_type);
    }

    in property editor_output_ports_model <=> editor.output_ports_model;
    in-out property <int> editor_output_selected_port_index <=> editor.output_selected_port_index;
    callback editor_output_connect_port <=> editor.output_connect_port;
    callback editor_output_refresh_ports <=> editor.output_refresh_ports;
    public function editor_output_focus() {
        editor.output_focus();
    }
    public function editor_output_show_connected_port_name(name: string, message_type: MessageType) {
        editor.output_show_connected_port_name(name, message_type);
    }

    in property instru_input_ports_model <=> instr.input_ports_model;
    in-out property <int> instru_input_selected_port_index <=> instr.input_selected_port_index;
    callback instru_input_connect_port <=> instr.input_connect_port;
    callback instru_input_refresh_ports <=> instr.input_refresh_ports;
    public function instru_input_focus() {
        instr.input_focus();
    }
    public function instru_input_show_connected_port_name(name: string, message_type: MessageType) {
        instr.input_show_connected_port_name(name, message_type);
    }

    in property instru_output_ports_model <=> instr.output_ports_model;
    in-out property <int> instru_output_selected_port_index <=> instr.output_selected_port_index;
    callback instru_output_connect_port <=> instr.output_connect_port;
    callback instru_output_refresh_ports <=> instr.output_refresh_ports;
    public function instru_output_focus() {
        instr.output_focus();
    }
    public function instru_output_show_connected_port_name(name: string, message_type: MessageType) {
        instr.output_show_connected_port_name(name, message_type);
    }

    VerticalLayout {
        alignment: start; // Stops spreading out when window lenghthened.
        padding_left: 10px;
        VerticalLayout {
            padding_top: 5px;
            padding-right: 10px;
            GroupBox {
                title: "From PitchGrid";
                width: 680px;
                VerticalLayout {
                    HorizontalLayout {
                        alignment: space-between;
                        ParamName { text: "Depth"; }
                        ParamName { text: "Root Freq"; }
                        ParamName { text: "Stretch"; }
                        ParamName { text: "Skew"; }
                        ParamName { text: "Mode Offset"; }
                        ParamName { text: "Steps"; }
                    }
                    HorizontalLayout {
                        alignment: space-between;
                        depth_value := ParamValue {}
                        root_freq_value := ParamValue {}
                        stretch_value := ParamValue {}
                        skew_value := ParamValue {}
                        mode_offset_value := ParamValue {}
                        steps_value := ParamValue {}
                    }
                }
            }
        }
        VerticalBox {
            padding-top: 10px;
            pitchgrid_connection_status_text := MessageText {
                horizontal_alignment: center;
                vertical_alignment: top;
            }
        }
        HorizontalLayout {
            padding_top: 5px;
            MagicText {
                text: "Pitch table:";
                vertical_alignment: center;
                width: 90px;
            }
            VerticalLayout {
                padding_left: Globals.horizontal_padding;
                padding_right: Globals.horizontal_padding * 2;
                pitch_tables_combo := ComboBox {
                    current_index: root.selected_pitch_table_index;
                    changed current_index => {
                        root.selected_pitch_table_changed(self.current_index);
                    }
                    height: Globals.control_height;
                    width: 55px;
                }
            }
//            HorizontalLayout {
//                alignment: end;
//                padding-right: 20px;
//                update_tuning_button := FilledButton {
//                    text: "Update Tuning";
//                    action: ButtonAction.primary;
//                    height: Globals.control_height;
//                    width: Globals.button_width;
//                    clicked => {
//                        root.update_tuning()
//                    }
//                }
//            }
        }
        VerticalLayout {
            padding_top: 10px;
            editor := MidiIo {
                group_title: "From/to Editor (Instrument Ports)";
            }
        }
        VerticalLayout {
            padding_top: 15px;
            instr := MidiIo {
                group_title: "From/To Instrument";
            }
        }
        HorizontalLayout {
            padding_top: 10px;
            padding_bottom: 5px;
            HorizontalLayout {
                alignment: start; // Centres the message text.
                Image {
                    source: Globals.icon;
                    width:  Globals.control_height; height: Globals.control_height;
                }
            }
            VerticalBox {
                padding-top: 5px;
                message_text := MessageText {
                    horizontal_alignment: center;
                    vertical_alignment: top;
                }
            }
            HorizontalLayout {
                alignment: end;
                padding-right: 10px;
                FilledButton {
                    prefix_icon: @image-url("images/menu-svgrepo-com.svg");
                    height: Globals.control_height;
                    width: 50px; // Min before icon is not centred.
                }
            }
        }
    }
}
